import CustomError from "./CustomError";

class NotFoundException extends CustomError{
    constructor(message: string = 'Dados n√£o encontrado'){
        super(message, 404)

    }
}

export default NotFoundException;